development:
  adapter: mysql2
  database: library_development
  username: familymap
  password: familymap
  host: localhost
test:
  adapter: mysql2
  database: library_test
  username: familymap
  password: familymap
  host: localhost
production:
  adapter: mysql2
  database: library_production
  username: familymap
  password: familymap
  host: localhost
